#!/usr/bin/env perl

use strict;
use warnings;
no warnings 'portable';

my $current_addr = 0;
my $previous_addr  = 0;
my $previous_len   = 0;
my $chunk_len = 0;
my $p = 0;

while (<>) { 
    m/LABEL:(\S+) g:\d+ nc:\d+ addr:([a-z\d]+) size:(\d+)/g;
    $current_addr = hex($2);
    if (($previous_addr + $previous_len) ne $current_addr) {
        if ($chunk_len gt 0) {
            print "$chunk_len\n";
        }
        $p = $1;
        $chunk_len = 0;
        print "LABEL:$p g:0 nc:0 addr:$2 size:";
    }
    $chunk_len += $3;
    $previous_addr = $current_addr;
    $previous_len  = $3;
}

print "$chunk_len\n";
